indexSuccess:
  stylesheets:    [shortblog.css, randomimage.css, nivo-slider.css, default.css]
  javascripts:    [jquery.nivo.slider.js,jquery.nivo.slider.pack.js]

404Success:
  stylesheets:    [links.css]

aboutUsSuccess:
  stylesheets:    [aside.css, randomimage.css]

welcomeSuccess:
  stylesheets:    [aside.css, randomimage.css]

rulesSuccess:
  stylesheets:    [aside.css, randomimage.css]

importantSuccess:
  stylesheets:    [aside.css, randomimage.css]

donateSuccess:
  stylesheets:    [aside.css, randomimage.css]
  javascripts:    [justgage.1.0.1.min.js, raphael.2.1.0.min.js]
  
donateThanksSuccess:
  stylesheets:    [aside.css, randomimage.css]