<?php

/**
 * BaseEventmyCharacter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mycharacter_id
 * @property integer $event_id
 * @property boolean $approved
 * @property boolean $maybe
 * @property boolean $backup
 * @property myCharacter $myCharacter
 * @property Event $Event
 * 
 * @method integer          getId()             Returns the current record's "id" value
 * @method integer          getMycharacterId()  Returns the current record's "mycharacter_id" value
 * @method integer          getEventId()        Returns the current record's "event_id" value
 * @method boolean          getApproved()       Returns the current record's "approved" value
 * @method boolean          getMaybe()          Returns the current record's "maybe" value
 * @method boolean          getBackup()         Returns the current record's "backup" value
 * @method myCharacter      getMyCharacter()    Returns the current record's "myCharacter" value
 * @method Event            getEvent()          Returns the current record's "Event" value
 * @method EventmyCharacter setId()             Sets the current record's "id" value
 * @method EventmyCharacter setMycharacterId()  Sets the current record's "mycharacter_id" value
 * @method EventmyCharacter setEventId()        Sets the current record's "event_id" value
 * @method EventmyCharacter setApproved()       Sets the current record's "approved" value
 * @method EventmyCharacter setMaybe()          Sets the current record's "maybe" value
 * @method EventmyCharacter setBackup()         Sets the current record's "backup" value
 * @method EventmyCharacter setMyCharacter()    Sets the current record's "myCharacter" value
 * @method EventmyCharacter setEvent()          Sets the current record's "Event" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventmyCharacter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eventmy_character');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('mycharacter_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('approved', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('maybe', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('backup', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('myCharacter', array(
             'local' => 'mycharacter_id',
             'foreign' => 'id'));

        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));
    }
}