<?php

/**
 * BasePostTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $post_id
 * @property integer $tag_id
 * @property Post $Post
 * @property Tag $Tag
 * 
 * @method integer getID()      Returns the current record's "ID" value
 * @method integer getPostId()  Returns the current record's "post_id" value
 * @method integer getTagId()   Returns the current record's "tag_id" value
 * @method Post    getPost()    Returns the current record's "Post" value
 * @method Tag     getTag()     Returns the current record's "Tag" value
 * @method PostTag setID()      Sets the current record's "ID" value
 * @method PostTag setPostId()  Sets the current record's "post_id" value
 * @method PostTag setTagId()   Sets the current record's "tag_id" value
 * @method PostTag setPost()    Sets the current record's "Post" value
 * @method PostTag setTag()     Sets the current record's "Tag" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post_tag');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id'));
    }
}