<?php

/**
 * BaseAdminLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $description
 * @property integer $created_at
 * @property integer $user_id
 * @property User $User
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method clob     getDescription() Returns the current record's "description" value
 * @method integer  getCreatedAt()   Returns the current record's "created_at" value
 * @method integer  getUserId()      Returns the current record's "user_id" value
 * @method User     getUser()        Returns the current record's "User" value
 * @method AdminLog setId()          Sets the current record's "id" value
 * @method AdminLog setDescription() Sets the current record's "description" value
 * @method AdminLog setCreatedAt()   Sets the current record's "created_at" value
 * @method AdminLog setUserId()      Sets the current record's "user_id" value
 * @method AdminLog setUser()        Sets the current record's "User" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdminLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_log');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('created_at', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}