<?php

/**
 * BasemyCharacterLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mycharacter_id
 * @property integer $mycharacter_type_id
 * @property clob $description
 * @property integer $created_at
 * @property myCharacter $myCharacter
 * @property myCharacterLogType $myCharacterLogType
 * 
 * @method integer            getId()                  Returns the current record's "id" value
 * @method integer            getMycharacterId()       Returns the current record's "mycharacter_id" value
 * @method integer            getMycharacterTypeId()   Returns the current record's "mycharacter_type_id" value
 * @method clob               getDescription()         Returns the current record's "description" value
 * @method integer            getCreatedAt()           Returns the current record's "created_at" value
 * @method myCharacter        getMyCharacter()         Returns the current record's "myCharacter" value
 * @method myCharacterLogType getMyCharacterLogType()  Returns the current record's "myCharacterLogType" value
 * @method myCharacterLog     setId()                  Sets the current record's "id" value
 * @method myCharacterLog     setMycharacterId()       Sets the current record's "mycharacter_id" value
 * @method myCharacterLog     setMycharacterTypeId()   Sets the current record's "mycharacter_type_id" value
 * @method myCharacterLog     setDescription()         Sets the current record's "description" value
 * @method myCharacterLog     setCreatedAt()           Sets the current record's "created_at" value
 * @method myCharacterLog     setMyCharacter()         Sets the current record's "myCharacter" value
 * @method myCharacterLog     setMyCharacterLogType()  Sets the current record's "myCharacterLogType" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemyCharacterLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_character_log');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('mycharacter_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mycharacter_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('created_at', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('myCharacter', array(
             'local' => 'mycharacter_id',
             'foreign' => 'id'));

        $this->hasOne('myCharacterLogType', array(
             'local' => 'mycharacter_type_id',
             'foreign' => 'id'));
    }
}