<?php

/**
 * BaseCraftInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Crafts
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getCrafts() Returns the current record's "Crafts" collection
 * @method CraftInfo           setId()     Sets the current record's "id" value
 * @method CraftInfo           setName()   Sets the current record's "name" value
 * @method CraftInfo           setCrafts() Sets the current record's "Crafts" collection
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCraftInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('craft_info');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Craft as Crafts', array(
             'local' => 'id',
             'foreign' => 'craft_info_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}