<?php

/**
 * BaseExtraType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property Doctrine_Collection $Extras
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getCode()   Returns the current record's "code" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getExtras() Returns the current record's "Extras" collection
 * @method ExtraType           setId()     Sets the current record's "id" value
 * @method ExtraType           setCode()   Sets the current record's "code" value
 * @method ExtraType           setName()   Sets the current record's "name" value
 * @method ExtraType           setExtras() Sets the current record's "Extras" collection
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtraType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extra_type');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Extra as Extras', array(
             'local' => 'id',
             'foreign' => 'extra_type_id'));
    }
}