<?php

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Images
 * @property Doctrine_Collection $ImageAlbum
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getImages()     Returns the current record's "Images" collection
 * @method Doctrine_Collection getImageAlbum() Returns the current record's "ImageAlbum" collection
 * @method Album               setId()         Sets the current record's "id" value
 * @method Album               setName()       Sets the current record's "name" value
 * @method Album               setImages()     Sets the current record's "Images" collection
 * @method Album               setImageAlbum() Sets the current record's "ImageAlbum" collection
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Image as Images', array(
             'refClass' => 'ImageAlbum',
             'local' => 'album_id',
             'foreign' => 'image_id'));

        $this->hasMany('ImageAlbum', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}