<?php

/**
 * BaseImageImageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $image_id
 * @property integer $image_type_id
 * @property Image $Image
 * @property ImageType $ImageType
 * 
 * @method integer        getID()            Returns the current record's "ID" value
 * @method integer        getImageId()       Returns the current record's "image_id" value
 * @method integer        getImageTypeId()   Returns the current record's "image_type_id" value
 * @method Image          getImage()         Returns the current record's "Image" value
 * @method ImageType      getImageType()     Returns the current record's "ImageType" value
 * @method ImageImageType setID()            Sets the current record's "ID" value
 * @method ImageImageType setImageId()       Sets the current record's "image_id" value
 * @method ImageImageType setImageTypeId()   Sets the current record's "image_type_id" value
 * @method ImageImageType setImage()         Sets the current record's "Image" value
 * @method ImageImageType setImageType()     Sets the current record's "ImageType" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageImageType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_image_type');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasOne('ImageType', array(
             'local' => 'image_type_id',
             'foreign' => 'id'));
    }
}