<?php

/**
 * BasemyCharacterLogType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $myCharacterLogs
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getMyCharacterLogs() Returns the current record's "myCharacterLogs" collection
 * @method myCharacterLogType  setId()              Sets the current record's "id" value
 * @method myCharacterLogType  setName()            Sets the current record's "name" value
 * @method myCharacterLogType  setMyCharacterLogs() Sets the current record's "myCharacterLogs" collection
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemyCharacterLogType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_character_log_type');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('myCharacterLog as myCharacterLogs', array(
             'local' => 'id',
             'foreign' => 'mycharacter_type_id'));
    }
}