<?php

/**
 * BaseImageAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $image_id
 * @property integer $album_id
 * @property Image $Image
 * @property Album $Album
 * 
 * @method integer    getID()       Returns the current record's "ID" value
 * @method integer    getImageId()  Returns the current record's "image_id" value
 * @method integer    getAlbumId()  Returns the current record's "album_id" value
 * @method Image      getImage()    Returns the current record's "Image" value
 * @method Album      getAlbum()    Returns the current record's "Album" value
 * @method ImageAlbum setID()       Sets the current record's "ID" value
 * @method ImageAlbum setImageId()  Sets the current record's "image_id" value
 * @method ImageAlbum setAlbumId()  Sets the current record's "album_id" value
 * @method ImageAlbum setImage()    Sets the current record's "Image" value
 * @method ImageAlbum setAlbum()    Sets the current record's "Album" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_album');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasOne('Album', array(
             'local' => 'album_id',
             'foreign' => 'id'));
    }
}