<?php

/**
 * BaseCraft
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $level
 * @property integer $my_character_id
 * @property integer $craft_info_id
 * @property boolean $visible
 * @property myCharacter $myCharacter
 * @property CraftInfo $CraftInfo
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getLevel()           Returns the current record's "level" value
 * @method integer     getMyCharacterId()   Returns the current record's "my_character_id" value
 * @method integer     getCraftInfoId()     Returns the current record's "craft_info_id" value
 * @method boolean     getVisible()         Returns the current record's "visible" value
 * @method myCharacter getMyCharacter()     Returns the current record's "myCharacter" value
 * @method CraftInfo   getCraftInfo()       Returns the current record's "CraftInfo" value
 * @method Craft       setId()              Sets the current record's "id" value
 * @method Craft       setLevel()           Sets the current record's "level" value
 * @method Craft       setMyCharacterId()   Sets the current record's "my_character_id" value
 * @method Craft       setCraftInfoId()     Sets the current record's "craft_info_id" value
 * @method Craft       setVisible()         Sets the current record's "visible" value
 * @method Craft       setMyCharacter()     Sets the current record's "myCharacter" value
 * @method Craft       setCraftInfo()       Sets the current record's "CraftInfo" value
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCraft extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('craft');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'unique' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('my_character_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('craft_info_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('myCharacter', array(
             'local' => 'my_character_id',
             'foreign' => 'id'));

        $this->hasOne('CraftInfo', array(
             'local' => 'craft_info_id',
             'foreign' => 'id'));
    }
}