<?php
// auto-generated by sfViewConfigHandler
// date: 2012/06/16 21:58:11
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'albumSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'imageSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'The Dutch Fellowship', false, false);
  $response->addMeta('description', 'Een Nederlandse Guild wars 2 guild.', false, false);
  $response->addMeta('keywords', 'Guild wars 2, guild, guildwars, guild wars, tdf, The Dutch Fellowship, Dutch guild, Nederlandse guild, Nederlands, clan, arena net, arena, ncsoft, nederland clan, nederlandse clan', false, false);
  $response->addMeta('language', 'nl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('iefix.css', '', array (  'condition' => 'lt IE 9',));
  $response->addStylesheet('gallery.css', '', array ());
  $response->addStylesheet('randomimage.css', '', array ());
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('ringbearer.font.js', '', array ());
  $response->addJavascript('cufon.declare.js', '', array ());
  $response->addJavascript('fixhtml5.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', '', array ());
}
else if ($templateName.$this->viewName == 'albumSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'The Dutch Fellowship', false, false);
  $response->addMeta('description', 'Een Nederlandse Guild wars 2 guild.', false, false);
  $response->addMeta('keywords', 'Guild wars 2, guild, guildwars, guild wars, tdf, The Dutch Fellowship, Dutch guild, Nederlandse guild, Nederlands, clan, arena net, arena, ncsoft, nederland clan, nederlandse clan', false, false);
  $response->addMeta('language', 'nl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('iefix.css', '', array (  'condition' => 'lt IE 9',));
  $response->addStylesheet('gallery.css', '', array ());
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('ringbearer.font.js', '', array ());
  $response->addJavascript('cufon.declare.js', '', array ());
  $response->addJavascript('fixhtml5.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', '', array ());
}
else if ($templateName.$this->viewName == 'imageSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'The Dutch Fellowship', false, false);
  $response->addMeta('description', 'Een Nederlandse Guild wars 2 guild.', false, false);
  $response->addMeta('keywords', 'Guild wars 2, guild, guildwars, guild wars, tdf, The Dutch Fellowship, Dutch guild, Nederlandse guild, Nederlands, clan, arena net, arena, ncsoft, nederland clan, nederlandse clan', false, false);
  $response->addMeta('language', 'nl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('iefix.css', '', array (  'condition' => 'lt IE 9',));
  $response->addStylesheet('gallery.css', '', array ());
  $response->addStylesheet('prettyPhoto.css', '', array ());
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('ringbearer.font.js', '', array ());
  $response->addJavascript('cufon.declare.js', '', array ());
  $response->addJavascript('fixhtml5.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', '', array ());
  $response->addJavascript('jquery.prettyPhoto.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'The Dutch Fellowship', false, false);
  $response->addMeta('description', 'Een Nederlandse Guild wars 2 guild.', false, false);
  $response->addMeta('keywords', 'Guild wars 2, guild, guildwars, guild wars, tdf, The Dutch Fellowship, Dutch guild, Nederlandse guild, Nederlands, clan, arena net, arena, ncsoft, nederland clan, nederlandse clan', false, false);
  $response->addMeta('language', 'nl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('iefix.css', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('ringbearer.font.js', '', array ());
  $response->addJavascript('cufon.declare.js', '', array ());
  $response->addJavascript('fixhtml5.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', '', array ());
}

