<?php

/**
 * CraftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CraftTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CraftTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Craft');
    }
}