<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdf
 * @subpackage model
 * @author     Olmo Buining
 */
class Event extends BaseEvent
{
	public function checkForUser($id) {
		foreach ($this->myCharacters as $character) {
			if ($character->User->id == $id) {
				
				return true;	
			}
		}
		return false;
	}
	
	public function getSignedCharacter($id) {
		foreach ($this->myCharacters as $character) {
			if ($character->User->id == $id) {
				
				return $character;	
			}
		}
		return false;
	}
	
	public function getApprovedCharacters($limit = 0) {
		$q = Doctrine_Query::create()
			->from('EventmyCharacter ec')
			->innerJoin('ec.myCharacter')
			->where('ec.event_id = ?', $this->id)
			->andWhere('ec.approved = ?', true)
			->limit($limit);
		 
		return $q->execute();
	}
	
	
	public function getMaybeCharacters($limit = 0) {
		$q = Doctrine_Query::create()
			->from('EventmyCharacter ec')
			->where('ec.event_id = ?', $this->id)
			->andWhere('ec.maybe = ?', true)
			->limit($limit);
		 
		return $q->execute();
	}
	
	
	public function getBackupCharacters($limit = 0) {
		$q = Doctrine_Query::create()
			->from('EventmyCharacter ec')
			->where('ec.event_id = ?', $this->id)
			->andWhere('ec.backup = ?', true)
			->limit($limit);
		 
		return $q->execute();
	}
	
	
	public function getPendingCharacters($limit = 0) {
		$q = Doctrine_Query::create()
			->from('EventmyCharacter ec')
			->where('ec.event_id = ?', $this->id)
			->andWhere('ec.backup = ?', false)
			->andWhere('ec.maybe = ?', false)
			->andWhere('ec.approved = ?', false)
			->limit($limit);
		 
		return $q->execute();
	}
	
	
	public function getAllSignups($limit = 0) {
		$q = Doctrine_Query::create()
			->from('EventmyCharacter ec')
			->where('ec.event_id = ?', $this->id)
			->limit($limit);
		 
		return $q->execute();
	}
}
