<?php

/**
 * EventmyCharacterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventmyCharacterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventmyCharacterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventmyCharacter');
    }
	
	public function getLink($eventId, $charId) {
		$q = Doctrine_Query::create()
			->from('EventmyCharacter ec')
			->where('ec.event_id = ?', $eventId)
			->andWhere('ec.mycharacter_id = ?', $charId);
		 
		return $q->fetchOne();
	}
}