<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }
	
	public function getAllInRange($startDay, $endDay, $limit = 0) {
		$q = Doctrine_Query::create()
			->from('Event e')
			->where('e.start > ?', $startDay)
			->andWhere('e.start < ?', $endDay)
			->orderBy('e.start ASC')
			->limit($limit);
		 
		return $q->execute();
		
	}
	
	
	public function getNextEvents($limit = 5) {
		$q = Doctrine_Query::create()
			->from('Event e')
			->where('e.start > ?', time())
			->orderBy('e.start ASC')
			->limit($limit);
		 
		return $q->execute();
	}
}