<?php

/**
 * ExtraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Extra');
    }
	
	
	
	public function OnlineUsers() {
		$q = Doctrine_Query::create()
			->from('Extra e')
			->innerJoin('e.ExtraType et')
			->where('et.code = ?', 'LAST-ONL')
			->andWhere('e.updated_at > ?', time()-300);
		 
		return $q->execute();
	}
}