<?php

/**
 * ExtraTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraType');
    }
}