<?php

/**
 * imageTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class imageTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object imageTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('imageTag');
    }
	
	public function getLink($tag, $image) {
		$q = Doctrine_Query::create()
			->from('imageTag p')
			->where('p.image_id = ?', $image)
			->andWhere('p.tag_id = ?', $tag);
		 
		return $q->fetchOne();
		
	}
	
	public function getTagsWithImageId($imageid) {
		$q = Doctrine_Query::create()
			->from('Tag t')
			->innerJoin('t.imageTag it')
			->where('it.image_id = ?', $imageid)
			->orderBy('t.name asc');
		 
		return $q->execute();
		
	}
}