<?php

/**
 * Image_TypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Image_TypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageType');
    }
}