<?php

/**
 * ImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Image');
    }
	public function getRandomImage() {
		$q = Doctrine_Query::create()
			->from('Image i')
			->innerJoin('i.ImageTypes it')
			->where('it.id = ?', 5)
			->orderBy('RAND()');
		 
		return $q->fetchOne();
	}
	public function getAll($limit = 0, $orderBy = 'title') {
		$q = Doctrine_Query::create()
			->from('Image i')
			->orderBy('i.'.$orderBy)
			->limit($limit);
		 
		return $q->execute();	
	}
}