<?php

/**
 * ImageAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageAlbum');
    }
}