<?php

/**
 * ImageAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ImageAlbum extends BaseImageAlbum
{
	public function checkLink() {
		$q = Doctrine_Query::create()
			->from('ImageAlbum p')
			->where('p.image_id = ?', $this->image_id)
			->andWhere('p.album_id = ?', $this->album_id);
		 
		$result = $q->execute();
		if(count($result) > 0) {
			return true;	
		} else {
			return false;	
		}
		
	}
}
