<?php

/**
 * myCharacterLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myCharacterLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCharacterLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCharacterLog');
    }
	
	public function getLastLogs($limit=0) {
		$q = Doctrine_Query::create()
			->from('myCharacterLog cl')
			->orderBy('cl.created_at DESC')
			->limit($limit);
		 
		return $q->execute();
	}
	
	public function getLastNewCharacters($limit=0) {
		$q = Doctrine_Query::create()
			->from('myCharacterLog cl')
			->where("cl.description LIKE '%nieuw%'")
			->orderBy('cl.created_at DESC')
			->limit($limit);
		 
		return $q->execute();
	}
	
	public function getLastLog() {
		$q = Doctrine_Query::create()
			->from('myCharacterLog cl')
			->orderBy('cl.id DESC')
			->limit(1);
			
		return $q->fetchOne();
	}
	
	public function getNewLogs($limit=0) {
		$q = Doctrine_Query::create()
			->from('myCharacterLog cl')
			->where("cl.mycharacter_type_id = 0")
			->orderBy('cl.created_at DESC')
			->limit($limit);
		 
		return $q->execute();
	}
}