<?php

/**
 * myCharacterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myCharacterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object myCharacterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myCharacter');
    }
	
	public function getAllMains($limit=0) {
		$q = Doctrine_Query::create()
			->from('myCharacter c')
			->where('c.main = ?', true)
			->orderBy('c.name asc')
			->limit($limit);
		 
		return $q->execute();		
	}
	
	public function search($parameters, $limit=0) {
		if (!isset($parameters['level'])) {
			$parameters['level'] = 0;
		}
	
		$q = Doctrine_Query::create()
			->from('myCharacter c')
			->where('c.level > ?', $parameters['level'])
			->orderBy('c.name asc')
			->limit($limit);
			
			if ($parameters['main'] == 'ja') {
				$main = true;
				$q->andWhere('c.main = ?', $main);
			} elseif ($parameters['main'] == 'nee'){
				$main = false;
				$q->andWhere('c.main = ?', $main);
			} 
			if (!empty($parameters['races'])) {
				$q->andWhere('c.race_id = ?', $parameters['races']);
			}
			if (!empty($parameters['professions'])) {
				$q->andWhere('c.profession_id = ?', $parameters['professions']);
			}
			
		return $q->execute();		
	}
}