<?php

/**
 * Post_TypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Post_TypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Post_TypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post_Type');
    }
}