<?php

/**
 * PostTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdf
 * @subpackage model
 * @author     Olmo Buining
 */
class PostTag extends BasePostTag
{
	
	public function checkLink() {
		$q = Doctrine_Query::create()
			->from('PostTag p')
			->where('p.post_id = ?', $this->post_id)
			->andWhere('p.tag_id = ?', $this->tag_id);
		 
		$result = $q->execute();
		if(count($result) > 0) {
			return true;	
		} else {
			return false;	
		}
		
	}
}
