<?php

/**
 * postImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class postImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object postImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('postImage');
    }
}