<?php

/**
 * postTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class postTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object postTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('postTag');
    }
	
	public function getLink($tag, $post) {
		$q = Doctrine_Query::create()
			->from('postTag p')
			->where('p.post_id = ?', $post)
			->andWhere('p.tag_id = ?', $tag);
		 
		return $q->fetchOne();
		
	}
	
	
	public function getTagsWithBlogId($blogid) {
		$q = Doctrine_Query::create()
			->from('Tag t')
			->innerJoin('t.postTag it')
			->where('it.post_id = ?', $blogid)
			->orderBy('t.name asc');
		 
		return $q->execute();
	}
}