<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
	public function getRelatedBlogs($limit=0) {
		$returnBlogs = array();
		$ids = array();
		foreach ($this->Tags as $tag) {
			array_push($ids, $tag->id);
		}
		
		
		$q = Doctrine_Query::create()
			->from('Post p')
			->innerJoin('p.PostTag pt')
			->whereIn('pt.tag_id', $ids)
			->andWhere('p.id != ?', $this->id)
			->orderBy('p.created_at DESC')
			->limit($limit);;
		 
		return $q->execute();
	}
	
	
	public function getMainImage() {
		$q = Doctrine_Query::create()
			->from('Image i')
			->innerJoin('i.PostImage pi')
			->innerJoin('i.ImageImageType it')
			->where('pi.post_id = ?', $this->id)
			->andWhere('it.image_type_id = ?', 1);
		 
		return $q->fetchOne();
	}
	
	
	public function getSubImages() {
		$q = Doctrine_Query::create()
			->from('Image i')
			->innerJoin('i.PostImage pi')
			->innerJoin('i.ImageImageType it')
			->where('pi.post_id = ?', $this->id)
			->andWhere('it.image_type_id = ?', 2);
		 
		return $q->execute();
	}
}
