<?php

/**
 * PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }
	
	public function getAll($limit = 0, $orderby = null) {
		$q = Doctrine_Query::create()
			->from('Post t')
			->limit($limit);
		
		if($orderby != null) {
			$q->orderBy('t.'.$orderby);
		}
		
		return $q->execute();	
	}
	
	public function getLastPostsByType($type, $limit = 0) {
		$q = Doctrine_Query::create()
			->from('Post p')
			->innerJoin('p.PostType pt')
			->where('pt.id = ?', $type)
			->orderBy('p.created_at DESC')
			->limit($limit);
		 
		return $q->execute();
	}
	public function getAllPostsByType($type,$offset = 0, $limit = 5) {
		$q = Doctrine_Query::create()
			->from('Post p')
			->innerJoin('p.PostType pt')
			->where('pt.id = ?', $type)
			->orderBy('p.created_at DESC')
			->offset($offset)
			->limit($limit);
		 
		return $q->execute();
	}
}