<?php

/**
 * Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tag extends BaseTag
{
	public function getBlogs() {
		$blogs = array();
		foreach($this->Posts as $blog) {
			$blogs[$blog->id] = $blog;
		}
		return $blogs;
	}
	public function getImages($limit = 0) {
		$q = Doctrine_Query::create()
			->from('Image i')
			->innerJoin('i.Tags t')
			->where('t.id = ?', $this->id)
			->orderBy('i.created_at DESC')
			->limit($limit);
		 
		return $q->execute();
	}
}
