document.createElement('header');
document.createElement('nav');
document.createElement('section');
document.createElement('article');
document.createElement('figure');
document.createElement('time');
document.createElement('aside');
document.createElement('footer');
document.createElement('hgroup');