indexSuccess:
  stylesheets:    [jquery-ui-1.8.18.custom.css, calendar.css]
  javascripts:    [jquery-ui-1.8.18.custom.min.js]

eventSuccess:
  stylesheets:    [gallery.css, aside.css]

newEventSuccess:
  stylesheets:    [forms.css]

newPublicEventSuccess:
  stylesheets:    [forms.css, jquery-ui-1.8.18.custom.css]
  javascripts:    [jquery-ui-1.8.18.custom.min.js]

editPublicEventSuccess:
  stylesheets:    [forms.css, jquery-ui-1.8.18.custom.css]
  javascripts:    [jquery-ui-1.8.18.custom.min.js]

editEventSuccess:
  stylesheets:    [forms.css]
