<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/14 19:43:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tdf',
  'username' => 'root',
  'password' => '123',
  'name' => 'doctrine',
)),);
