<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/09/14 19:57:16
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    '.settings' => 
    array (
      'csrf_secret' => 'c5190986e2a7f228d57b0196198ea9f1',
      'escaping_strategy' => true,
      'escaping_method' => 'ESC_SPECIALCHARS',
    ),
  ),
);
